/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DestinasiRouteImport } from './routes/destinasi'
import { Route as MembuatRouteImport } from './routes/membuat'
import { Route as PerjalananRouteImport } from './routes/perjalanan'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as ItineraryIdRouteImport } from './routes/itinerary.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinasiRoute = DestinasiRouteImport.update({
  id: '/destinasi',
  path: '/destinasi',
  getParentRoute: () => rootRouteImport,
} as any)
const MembuatRoute = MembuatRouteImport.update({
  id: '/membuat',
  path: '/membuat',
  getParentRoute: () => rootRouteImport,
} as any)
const PerjalananRoute = PerjalananRouteImport.update({
  id: '/perjalanan',
  path: '/perjalanan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryIdRoute = ItineraryIdRouteImport.update({
  id: '/itinerary/$id',
  path: '/itinerary/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/destinasi': typeof DestinasiRoute
  '/membuat': typeof MembuatRoute
  '/perjalanan': typeof PerjalananRoute
  '/planner': typeof PlannerRoute
  '/tentang': typeof TentangRoute
  '/itinerary/$id': typeof ItineraryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/destinasi': typeof DestinasiRoute
  '/membuat': typeof MembuatRoute
  '/perjalanan': typeof PerjalananRoute
  '/planner': typeof PlannerRoute
  '/tentang': typeof TentangRoute
  '/itinerary/$id': typeof ItineraryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/destinasi': typeof DestinasiRoute
  '/membuat': typeof MembuatRoute
  '/perjalanan': typeof PerjalananRoute
  '/planner': typeof PlannerRoute
  '/tentang': typeof TentangRoute
  '/itinerary/$id': typeof ItineraryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/destinasi'
    | '/membuat'
    | '/perjalanan'
    | '/planner'
    | '/tentang'
    | '/itinerary/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/destinasi'
    | '/membuat'
    | '/perjalanan'
    | '/planner'
    | '/tentang'
    | '/itinerary/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/destinasi'
    | '/membuat'
    | '/perjalanan'
    | '/planner'
    | '/tentang'
    | '/itinerary/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DestinasiRoute: typeof DestinasiRoute
  MembuatRoute: typeof MembuatRoute
  PerjalananRoute: typeof PerjalananRoute
  PlannerRoute: typeof PlannerRoute
  TentangRoute: typeof TentangRoute
  ItineraryIdRoute: typeof ItineraryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinasi': {
      id: '/destinasi'
      path: '/destinasi'
      fullPath: '/destinasi'
      preLoaderRoute: typeof DestinasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membuat': {
      id: '/membuat'
      path: '/membuat'
      fullPath: '/membuat'
      preLoaderRoute: typeof MembuatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perjalanan': {
      id: '/perjalanan'
      path: '/perjalanan'
      fullPath: '/perjalanan'
      preLoaderRoute: typeof PerjalananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary/$id': {
      id: '/itinerary/$id'
      path: '/itinerary/$id'
      fullPath: '/itinerary/$id'
      preLoaderRoute: typeof ItineraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DestinasiRoute: DestinasiRoute,
  MembuatRoute: MembuatRoute,
  PerjalananRoute: PerjalananRoute,
  PlannerRoute: PlannerRoute,
  TentangRoute: TentangRoute,
  ItineraryIdRoute: ItineraryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
